name: music-rec-app-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - textblob
  - requests
  - transformers
  - pytorch
  - pip
  - pip:
      - streamlit
      - spotipy
      - python-dotenv
